# Generated by Django 2.1.7 on 2019-05-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20190514_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date_published'),
        ),
    ]
