# Generated by Django 2.1.7 on 2019-05-14 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20190514_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='Status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
