# Generated by Django 2.1.7 on 2019-05-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20190514_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
