# Generated by Django 2.1.7 on 2019-05-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_child_category_products_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Updated_by',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
