# Generated by Django 2.2.1 on 2019-05-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_category_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Created_by',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
