# Generated by Django 2.2.1 on 2019-05-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Image',
            new_name='Image_five',
        ),
        migrations.AddField(
            model_name='products',
            name='Image_four',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='Image_one',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='Image_six',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='Image_three',
            field=models.ImageField(default=' ', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='Image_two',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
