# Generated by Django 2.2.1 on 2019-05-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20190529_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Child_Category_Name',
        ),
    ]
