# Generated by Django 2.2.1 on 2019-05-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_remove_products_child_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_category',
            name='Created_by',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='child_category',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='child_category',
            name='Updated_by',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
