# Generated by Django 2.2.1 on 2019-06-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20190601_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Category_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Category'),
        ),
    ]
