# Generated by Django 2.2.1 on 2019-06-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_auto_20190601_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Child_Category_Id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='Sub_Category_Id',
            field=models.IntegerField(),
        ),
    ]
