# Generated by Django 2.2.1 on 2019-06-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_auto_20190603_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Category_Id',
            field=models.IntegerField(),
        ),
    ]
