# Generated by Django 2.2.1 on 2019-06-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_auto_20190603_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Child_Category_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.Child_Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='Image_six',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
