# Generated by Django 2.2.1 on 2019-06-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_auto_20190603_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Child_Category_Id_get',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.Child_Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='Sub_Category_Id_get',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.Sub_Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='Child_Category_Id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='Sub_Category_Id',
            field=models.IntegerField(),
        ),
    ]
