# Generated by Django 2.2.1 on 2019-06-03 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_auto_20190603_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Child_Category_Id_get',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='leads.Child_Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Sub_Category_Id_get',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='leads.Sub_Category'),
        ),
    ]
