# Generated by Django 2.2.1 on 2019-06-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_auto_20190603_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Child_Category_Id_get',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Sub_Category_Id_get',
        ),
    ]
