# Generated by Django 2.2.1 on 2019-06-04 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0036_auto_20190604_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Category_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Category'),
        ),
    ]
