# Generated by Django 2.2.1 on 2019-06-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0038_auto_20190607_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image_five',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image_four',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image_one',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image_six',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image_three',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image_two',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
