# Generated by Django 2.2.1 on 2019-06-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0039_auto_20190608_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Child_Category_Id',
        ),
    ]
