# Generated by Django 2.2.1 on 2019-06-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0040_remove_products_child_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
                ('Moblie', models.CharField(max_length=300)),
                ('Password', models.CharField(max_length=300)),
                ('Status', models.IntegerField()),
                ('Created_by', models.CharField(max_length=300)),
                ('Updated_by', models.CharField(max_length=300)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
