# Generated by Django 2.2.1 on 2019-07-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0042_auto_20190620_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=200, unique=True)),
                ('Moblie', models.BigIntegerField(unique=True)),
                ('Password', models.CharField(max_length=300)),
                ('Status', models.IntegerField(default=0)),
                ('Created_by', models.CharField(blank=True, max_length=300)),
                ('Updated_by', models.CharField(blank=True, max_length=300)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='admin_register',
            name='Email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='admin_register',
            name='Moblie',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='admin_register',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
