# Generated by Django 2.2.1 on 2019-07-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0043_auto_20190701_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_register',
        ),
    ]
