# Generated by Django 2.2.1 on 2019-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0044_delete_admin_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=300)),
                ('Product_Id', models.CharField(max_length=300)),
                ('Unit_Price', models.IntegerField()),
                ('Offer_Price', models.IntegerField()),
                ('Image_one', models.CharField(max_length=300)),
                ('Product_Quote', models.CharField(max_length=300)),
                ('Product_Detail_Description', models.CharField(max_length=300)),
                ('Status', models.IntegerField()),
                ('Created_by', models.CharField(max_length=300)),
                ('Updated_by', models.CharField(max_length=300)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
