# Generated by Django 2.2.1 on 2019-07-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0045_viewcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcart',
            name='Quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregister',
            name='Email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='Moblie',
            field=models.BigIntegerField(),
        ),
    ]
