# Generated by Django 2.2.1 on 2019-07-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0046_auto_20190705_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='Email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='Moblie',
            field=models.BigIntegerField(unique=True),
        ),
    ]
